### ISSUE TITLE
Cross-build for Scala.js

### ISSUE THREAD

**Issue by milessabin** [gemini-hlsw/gsp-graphql#202]
This won't work for the doobie/skunk modules, but it should be fine for the others, and it would be interesting to get other backends contributed from the node ecosystem.

**Comment by armanbilge** [comment]
It _is_ doable for skunk, skunk runs on Node.js :)

As I mentioned in https://github.com/gemini-hlsw/gsp-graphql/issues/128#issuecomment-1135968136, this should be very easy for the actual sources. The difficulty right now are that your tests spin up Docker images directly, which will be difficult to port. If you're willing to make a change, here's two strategies:
- Setup the docker images externally, if possible. Skunk does this with Docker compose which is why it was easy to port its Node.js tests.
- Explore using a different client such as [whale-tail](https://github.com/davenverse/whale-tail) which cross-builds for JVM and Node.js.

**Comment by alexcardell** [comment]
TestContainers does have support for setting up arbitrary containers docker-compose files. 

There's also a testcontainers-node. Perhaps it's feasible to write some Scala.js testcontainers bindings to use the node/java docker-compose API depending on context?

**Comment by armanbilge** [comment]
@alexcardell thanks for chiming in. I mentioned there's already an existing pure Scala Docker client that cross-compiles for JVM and Node.js (and will cross-compile for Scala Native as well without additional work, once its dependencies are ported). So I think investing in that is the best long-term solution, rather trying to juggle different implementations for the different platforms (dealing npm is not much fun).

https://github.com/davenverse/whale-tail

**Comment by armanbilge** [comment]
This would benefit from https://github.com/gemini-hlsw/gsp-graphql/issues/128#issuecomment-1230772007.
