### ISSUE TITLE
Is there a Query renderer that generates valid queries?

### ISSUE THREAD

**Issue by dantb** [gemini-hlsw/gsp-graphql#369]
I'm trying to generate queries from a DSL that compiles to `Query` and test it by doing a round trip. With a couple of local adjustments to the rendering logic this now works for queries comprised of only `Select` and `Group` which fits my use case. Understandably it doesn't for the others which are human readable strings like `"<rename: ...>"` etc. 

This raises a question, have you written a `Query => String` function already somewhere? If not, do you think it would be a useful addition to the library? More of a client than a server concern, so perhaps a separate module...

**Comment by tpolecat** [comment]
I wrote [this one](https://github.com/gemini-hlsw/lucuma-odb/blob/main/modules/service/src/main/scala/lucuma/odb/graphql/util/PrettyPrinter.scala) and it works ok for our needs. It uses [Paiges](https://github.com/typelevel/paiges) so you say `PrettyPrinter.query(q).render(100)` for instance to get a string formatted for 100-char lines.

**Comment by milessabin** [comment]
`Query`, ie. the query algebra, is intentionally somewhat distant from the syntax. If you're able, I'd recommend starting from the AST rather than a `Query`. There's an example of rendering from the AST in [`QueryMinimizer`](https://github.com/gemini-hlsw/gsp-graphql/blob/1e7b7d79bfbda43eccf685697e3f396a1e3660a7/modules/core/src/main/scala/compiler.scala#L185-L306).

**Comment by dantb** [comment]
@milessabin implemented in terms of that and it's much nicer 😊  thanks!

I've also added a `doc"{ foo { bar} }"` `Document` literal, shall I open a PR with that here?
