### ISSUE TITLE
Invalid schema not flagged

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/gsp-graphql#377]
This schema is wrong but it is not flagged during parsing

```graphql
type ObservingMode {
  # instrument
  instrument: InstrumentType
}

type ImagingMode implements ObservingMode {
  # Wavelength in appropriate units
  wavelength: Wavelength!

  # instrument
  instrument: InstrumentType

  # params
  params: InstrumentITCParams!

}

type SpectroscopyMode implements ObservingMode {
  # Wavelength in appropriate units
  wavelength: Wavelength!

  # Resolution
  resolution: BigDecimal!

  # params
  params: InstrumentITCParams!

  # instrument
  instrument: InstrumentType
}
```

**Comment by milessabin** [comment]
I'm not seeing this ... for this test,

```graphql
type Query {
  foo: Foo
}

type Foo {
  foo: Int
}

type Bar implements Foo {
  foo: Int
  bar: String
}
```

The schema parser reports `Interface Foo implemented by Bar is not defined`. The message could be improved to indicate that Foo is a type rather than an interface, but it _is_ reporting an error.

How are you parsing the schema? Are you calling `SchemaParser.parseText` (which checks constraints) or `GraphQLParser.Document.parseAll` which just parses to an AST without checking any non-syntactic constraints?

**Comment by milessabin** [comment]
Error message improved in #402.

I won't close this just yet.

**Comment by milessabin** [comment]
Closing for now ... please reopen if you see any errors which aren't reported as either  a `Failure` or a `Warning`.
