### ISSUE TITLE
Schema permits duplicate enum values

### ISSUE THREAD

**Issue by keirlawson** [gemini-hlsw/gsp-graphql#92]
If I'm reading the spec correctly (and understanding the code correctly!) duplicate enum values in schemas should not be permitted (https://spec.graphql.org/June2018/#sec-Enums), but presently the following test fails:

```scala
val schema = Schema(
      """
         enum Direction {
          NORTH
          NORTH
        }
    """
    )

    assert(schema.isLeft)
```

Seems to me that we should be holding these values as a `Set` rather than a `List`? Happy to work on a fix if someone can clarify whether or not this is intended behaviour :)

**Comment by milessabin** [comment]
Good spot! I think a check for this really belongs in `SchemaValidator` rather than changing the data type.

At ITV we've adopted the convention of having tests for schema and mapping validity, in much the same way that we have tests for SQL query validity using doobie's `Checker`, eg.,

```scala
class ValidationSuite extends DatabaseSuite {
  test("schema is valid") {
    mapping match {
      case x: XXXMapping[IO] => assert(x.schema0.left.isEmpty)
      case _ => assert(false)
    }
  }

  test("mapping is valid") {
    assert(mapping.validate.isEmpty)
  }
}
```
where `schema0` is the result of `Schema(<... SDL literal ...>)`. The ergonomics of this could certainly be improved ... see eg. #70.
